config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :courses
  resources :promotions
  resources :courses do
    resources :exams
  end
  resources :exams do
    resources :evaluations
  end

  root to: 'home#index'
  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :teachers
end

app/models/evaluation.rb
# frozen_string_literal: true

class Evaluation < ApplicationRecord
  validates :grade, presence: true

  belongs_to :exam
  belongs_to :student, class_name: 'User'
  belongs_to :teacher, class_name: 'User'
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :only_teacher
  before_action :set_exam
  before_action :set_evaluation, only: %i[show edit update destroy]

  # GET /evaluations or /evaluations.json
  def index
    @evaluations = @exam.evaluations
  end

  # GET /evaluations/1 or /evaluations/1.json
  def show; end

  # GET /evaluations/new
  def new
    @evaluation = @exam.evaluations.new
  end

  # GET /evaluations/1/edit
  def edit; end

  # POST /evaluations or /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)

    respond_to do |format|
      if @evaluation.save
        format.html do
          redirect_to exam_evaluation_path(@evaluation.exam, @evaluation),
                      notice: 'Evaluation was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1 or /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html do
          redirect_to exam_evaluation_path(@evaluation.exam, @evaluation),
                      notice: 'Evaluation was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1 or /evaluations/1.json
  def destroy
    @evaluation.destroy

    respond_to do |format|
      format.html { redirect_to exam_evaluations_path, notice: 'Evaluation was successfully destroyed.' }
    end
  end

  private

  def set_exam
    @exam = Exam.find(params[:exam_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_evaluation
    @evaluation = @exam.evaluations.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def evaluation_params
    params.require(:evaluation).permit(:grade, :student_id).merge(teacher: current_user, exam: @exam)
  end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_evaluation.html.erb
<tr class="border-b">
  <td class="whitespace-nowrap px-6 py-4"><%= evaluation.grade%></td>
  <td class="whitespace-nowrap px-6 py-4"><%= evaluation.created_at%></td>
  <td class="whitespace-nowrap px-6 py-4"><%= evaluation.exam.course.title%></td>
  <td class="whitespace-nowrap px-6 py-4"><%= evaluation.student.full_name%></td>
  <td class="whitespace-nowrap px-6 py-4"><%= evaluation.teacher.full_name%></td>
  <% if action_name != "show" %>
    <td id="<%= dom_id evaluation %>" class="whitespace-nowrap px-6 py-4">
      <%= link_to "Show this exam", exam_evaluation_path(evaluation.exam, evaluation), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this exam', edit_exam_evaluation_path(evaluation.exam, evaluation), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    </td>
  <% end %>
</tr>

app/views/evaluations/_form.html.erb
<%= form_with(model: [exam, evaluation], class: "contents") do |form| %>
  <div class="mx-auto">
    <div class="flex flex-wrap -m-2">
      <% if evaluation.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>
          <ul>
            <% evaluation.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :grade, class: "leading-7 text-sm text-gray-600" %>
          <%= form.number_field :grade, in: 1.0..6, step: 0.5, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :student_id, class: "leading-7 text-sm text-gray-600" %>
          <%= form.select :student_id, evaluation.exam.students.map { |student| [student.full_name, student.id] } , class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<div class="mx-auto  w-full">
  <h1 class="font-bold text-4xl">Editing evaluation</h1>
  <%= render "form", exam: @exam, evaluation: @evaluation%>
  <%= link_to "Show this evaluation", exam_evaluation_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to evaluations", exam_evaluations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/evaluations/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Evaluation</h1>
    <%= link_to 'New evaluation', new_exam_evaluation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="text-sm font-light table-auto">
            <thead class="border-b font-medium">
              <tr class="text-left">
                <th scope="col" class="px-6 py-4">Grade</th>
                <th scope="col" class="px-6 py-4">Created at</th>
                <th scope="col" class="px-6 py-4">Course</th>
                <th scope="col" class="px-6 py-4">Student</th>
                <th scope="col" class="px-6 py-4">Teacher</th>
              </tr>
            </thead>
            <tbody id="evaluation">
              <% @evaluations.each do |evaluation| %>
                <%= render evaluation %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/evaluations/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl">New evaluation</h1>
  <%= render "form",  exam: @exam, evaluation: @evaluation %>
  <%= link_to 'Back to evaluations', exam_evaluations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/evaluations/show.html.erb
<div class="mx-auto w-full flex flex-col">
  <table class="text-sm font-light table-auto">
    <thead class="border-b font-medium">
      <tr class="text-left">
        <th scope="col" class="px-6 py-4">Grade</th>
        <th scope="col" class="px-6 py-4">Created at</th>
        <th scope="col" class="px-6 py-4">Course</th>
        <th scope="col" class="px-6 py-4">Student</th>
        <th scope="col" class="px-6 py-4">Teacher</th>
      </tr>
    </thead>
    <tbody id="grade">
      <%= render @evaluation %>
    </tbody>
  </table>
  <div class="flex justify-between items-center">
    <%= link_to 'Edit this evaluation', edit_exam_evaluation_path(@exam, @evaluation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this evaluation', exam_evaluation_path(@exam, @evaluation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to evaluations', exam_evaluations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>