config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :courses
  resources :promotions
  resources :courses do
    resources :exams
  end
  resources :exams do
    resources :evaluations
  end

  root to: 'home#index'
  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :teachers
end

app/models/promotion.rb
# frozen_string_literal: true

class Promotion < ApplicationRecord
  validates :name, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true

  has_many :students
  has_and_belongs_to_many :courses, join_table: :courses_promotions
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: %i[show edit update destroy]

  # GET /promotions or /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1 or /promotions/1.json
  def show; end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit; end

  # POST /promotions or /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)
    student_ids = params[:promotion][:student_ids]

    respond_to do |format|
      if @promotion.save
        @promotion.students = Student.where(id: student_ids.reject(&:empty?).map(&:to_i))
        format.html { redirect_to promotion_url(@promotion), notice: 'Promotion was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1 or /promotions/1.json
  def update
    student_ids = params[:promotion][:student_ids]
    respond_to do |format|
      if @promotion.update(promotion_params)
        @promotion.students = Student.where(id: student_ids.reject(&:empty?).map(&:to_i))

        format.html { redirect_to promotion_url(@promotion), notice: 'Promotion was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1 or /promotions/1.json
  def destroy
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def promotion_params
    params.require(:promotion).permit(:name, :start_at, :end_at)
  end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_with(model: promotion, class: "contents") do |form| %>
  <div class="mx-auto">
    <div class="flex flex-wrap -m-2">
      <% if promotion.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>
          <ul>
            <% promotion.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :name, class: "leading-7 text-sm text-gray-600" %><br>
          <%= form.text_field :name, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :start_at, class: "leading-7 text-sm text-gray-600" %>
          <%= form.date_field :start_at, value: "%Y-%m-%d", class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :end_at, class: "leading-7 text-sm text-gray-600" %>
          <%= form.date_field :end_at, value: "%Y-%m-%d", class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :student_ids, class: "leading-7 text-sm text-gray-600" %><br>
          <%= form.select :student_ids, options_for_select(Student.all.map{ |student| [student.full_name, student.id] }), { include_blank: true }, { class: "form-control", multiple: true } %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/promotions/_promotion.html.erb
<tr class="border-b">
  <td class="whitespace-nowrap px-6 py-4"><%= promotion.name%></td>
  <td class="whitespace-nowrap px-6 py-4">
    <%= promotion.courses.map { |course| course.title }.join("<br>").html_safe %>
  </td>
  <% if action_name == "show" %>
    <td class="whitespace-nowrap px-6 py-4">
      <%= promotion.students.map { |student| student.full_name }.join("<br>").html_safe %>
    </td>
  <% end %>
  <td class="whitespace-nowrap px-6 py-4"><%= promotion.start_at.strftime("%d %B, %Y")%></td>
  <td class="whitespace-nowrap px-6 py-4"><%= promotion.end_at.strftime("%d %B, %Y")%></td>
  <% if action_name != "show" %>
    <td id="<%= dom_id promotion %>" class="whitespace-nowrap px-6 py-4">
      <%= link_to "Show this promotion", promotion, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this promotion', edit_promotion_path(promotion), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    </td>
  <% end %>
</tr>

app/views/promotions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing promotion</h1>

  <%= render "form", promotion: @promotion %>

  <%= link_to "Show this promotion", @promotion, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to promotions", promotions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/promotions/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Promotions</h1>
    <%= link_to 'New course', new_promotion_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="text-sm font-light table-auto">
            <thead class="border-b font-medium">
              <tr class="text-left">
                <th scope="col" class="px-6 py-4">Name</th>
                <th scope="col" class="px-6 py-4">Courses</th>
                <th scope="col" class="px-6 py-4">Started at</th>
                <th scope="col" class="px-6 py-4">Ended at</th>
              </tr>
            </thead>
            <tbody id="promotions">
              <% @promotions.each do |promotion| %>
                <%= render promotion %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/promotions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New promotion</h1>

  <%= render "form", promotion: @promotion %>

  <%= link_to 'Back to promotions', promotions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/promotions/show.html.erb
<div class="mx-auto w-full flex flex-col">
  <table class="text-sm font-light table-auto">
    <thead class="border-b font-medium">
      <tr class="text-left">
        <th scope="col" class="px-6 py-4">Name</th>
        <th scope="col" class="px-6 py-4">Courses</th>
        <th scope="col" class="px-6 py-4">Students</th>
        <th scope="col" class="px-6 py-4">Started at</th>
        <th scope="col" class="px-6 py-4">Ended at</th>
      </tr>
    </thead>
    <tbody id="promotion">
      <%= render @promotion %>
    </tbody>
  </table>
  <div class="flex justify-between items-center">
    <%= link_to 'Edit this promotion', edit_promotion_path(@promotion), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this promotion', promotion_path(@promotion), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to promotions', promotions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>