config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :courses
  resources :promotions
  resources :courses do
    resources :exams
  end
  resources :exams do
    resources :evaluations
  end

  root to: 'home#index'
  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :teachers
end

app/models/exam.rb
class Exam < ApplicationRecord
  # attr_accessor :name, :consideration, :passed_at, :teacher, :course

  validates :name, presence: true
  validates :consideration, presence: true
  validates :passed_at, presence: true

  belongs_to :teacher, class_name: 'User'
  belongs_to :course
  has_many :evaluations, dependent: :destroy
  has_many :students, through: :course
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :only_teacher
  before_action :set_course
  before_action :set_exam, only: %i[show edit update destroy]

  # GET /exams
  def index
    @exams = @course.exams
  end

  # GET /exams/1 or /exams/1.json
  def show; end

  # GET /exams/new
  def new
    @exam = @course.exams.new
  end

  # GET /exams/1/edit
  def edit; end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to course_exam_url(@course, @exam), notice: 'Exam was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to course_exam_url(@course, @exam), notice: 'Exam was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam.destroy

    respond_to do |format|
      format.html { redirect_to course_exams_url(@course), notice: 'Exam was successfully destroyed.' }
    end
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def set_exam
    @exam = @course.exams.find(params[:id])
  end

  def exam_params
    params.require(:exam).permit(:name, :consideration, :passed_at).merge(teacher: current_user, course: @course)
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_exam.html.erb
<tr class="border-b">
  <td class="whitespace-nowrap px-6 py-4">  <%= link_to exam.name, exam_evaluations_path(exam), class: "text-gray-800 underline hover:text-gray-200" %>
  </td>
  <td class="whitespace-nowrap px-6 py-4"><%= exam.consideration%></td>
  <td class="whitespace-nowrap px-6 py-4"><%= exam.passed_at%></td>
  <td class="whitespace-nowrap px-6 py-4"><%= exam.teacher.full_name %></td>
  <td class="whitespace-nowrap px-6 py-4"><%= exam.course.title %></td>
  <% if action_name != "show" %>
    <td id="<%= dom_id exam %>" class="whitespace-nowrap px-6 py-4">
      <%= link_to "Show this exam", course_exam_path(exam.course, exam), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this exam', edit_course_exam_path(exam.course, exam), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    </td>
  <% end %>
</tr>

app/views/exams/_form.html.erb
<%= form_with(model:  [course, exam], class: "contents") do |form| %>
  <div class="mx-auto">
    <div class="flex flex-wrap -m-2">
      <% if exam.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>
          <ul>
            <% exam.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :name, class: "leading-7 text-sm text-gray-600" %>
          <%= form.text_field :name, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :consideration, class: "leading-7 text-sm text-gray-600" %>
          <%= form.number_field :consideration, in: 1.0..100.0, step: 1, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.label :passed_at, class: "leading-7 text-sm text-gray-600" %>
          <%= form.date_field :passed_at, value: "%Y-%m-%d", class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
        </div>
      </div>
      <div class="p-2 w-full">
        <div class="relative">
          <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/exams/edit.html.erb
<div class="mx-auto  w-full">
  <h1 class="font-bold text-4xl">Editing exam</h1>
  <%= render "form", course: @course, exam: @exam%>
  <%= link_to "Show this exam", course_exam_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to exams", course_exams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/exams/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Exams</h1>
    <%= link_to 'New exam', new_course_exam_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="text-sm font-light table-auto">
            <thead class="border-b font-medium">
              <tr class="text-left">
                <th scope="col" class="px-6 py-4">Name</th>
                <th scope="col" class="px-6 py-4">consideration</th>
                <th scope="col" class="px-6 py-4">Passed on</th>
                <th scope="col" class="px-6 py-4">Teacher</th>
                <th scope="col" class="px-6 py-4">Course</th>
              </tr>
            </thead>
            <tbody id="grade">
              <% @exams.each do |exam| %>
                <%= render exam %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/exams/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl">New exam</h1>
  <%= render "form", course: @course, exam: @exam %>
  <%= link_to 'Back to exams', course_exams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/exams/show.html.erb
<div class="mx-auto w-full flex flex-col">
  <table class="text-sm font-light table-auto">
    <thead class="border-b font-medium">
      <tr class="text-left">
        <th scope="col" class="px-6 py-4">Name</th>
        <th scope="col" class="px-6 py-4">consideration</th>
        <th scope="col" class="px-6 py-4">Passed on</th>
        <th scope="col" class="px-6 py-4">Teacher</th>
        <th scope="col" class="px-6 py-4">Course</th>
      </tr>
    </thead>
    <tbody id="grade">
      <%= render @exam %>
    </tbody>
  </table>
  <div class="flex justify-between items-center">
    <%= link_to 'Edit this exam', edit_course_exam_path(@course, @exam), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this exam', course_exam_path(@course, @exam), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to exams', course_exams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>