config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :courses
  resources :promotions
  resources :courses do
    resources :exams
  end
  resources :exams do
    resources :evaluations
  end

  root to: 'home#index'
  devise_for :students, controllers: { registrations: 'students/registrations' }
  devise_for :teachers
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true
  validates :slug, presence: true

  belongs_to :category, optional: true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  validates :title, presence: true
  validates :slug, presence: true, uniqueness: true

  belongs_to :quarter
  belongs_to :category
  has_many :exams, dependent: :destroy

  has_and_belongs_to_many :promotions, join_table: :courses_promotions
  has_and_belongs_to_many :teachers, join_table: :teacher_courses
  has_many :students, through: :promotions

  def to_s
    title
  end
end

app/models/evaluation.rb
# frozen_string_literal: true

class Evaluation < ApplicationRecord
  validates :grade, presence: true

  belongs_to :exam
  belongs_to :student, class_name: 'User'
  belongs_to :teacher, class_name: 'User'
end

app/models/exam.rb
class Exam < ApplicationRecord
  # attr_accessor :name, :consideration, :passed_at, :teacher, :course

  validates :name, presence: true
  validates :consideration, presence: true
  validates :passed_at, presence: true

  belongs_to :teacher, class_name: 'User'
  belongs_to :course
  has_many :evaluations, dependent: :destroy
  has_many :students, through: :course
end

app/models/person.rb
class Person < ApplicationRecord
    self.abstract_class = true

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
    validates :adress, presence: true
    validates :city, presence: true
    belongs_to :city
end

app/models/promotion.rb
# frozen_string_literal: true

class Promotion < ApplicationRecord
  validates :name, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true

  has_many :students
  has_and_belongs_to_many :courses, join_table: :courses_promotions
end

app/models/quarter.rb
# frozen_string_literal: true

class Quarter < ApplicationRecord
  validates :started_at, presence: true
  validates :ended_at, presence: true

  belongs_to :semester
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  validates :slug, presence: true
  validates :name, presence: true

  has_many :people, through: :person_roles
end

app/models/semester.rb
# frozen_string_literal: true

class Semester < ApplicationRecord
  validates :started_at, presence: true
  validates :ended_at, presence: true

  has_many :quarters
  has_many :students, through: :student_semesters
end

app/models/student.rb
# frozen_string_literal: true

class Student < User
  has_many :evaluations
  has_many :exams, through: :evaluations
  belongs_to :promotion, optional: true
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < User
  has_many :exams
  has_many :evaluations
  has_and_belongs_to_many :courses, join_table: :teacher_courses
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :adress, presence: true

  belongs_to :city

  before_create :set_city
  accepts_nested_attributes_for :city

  def student?
    is_a?(Student)
  end

  def teacher?
    is_a?(Teacher)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def set_city
    zip_code = city.zip_code
    name = city.name
    city = City.find_or_create_by(zip_code:, name:)
    self.city = city
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def tailwind_classes_for(flash_type)
    {
      notice: 'bg-green-400 border-l-4 border-green-700 text-white',
      error: 'bg-red-400 border-l-4 border-red-700 text-black'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/layouts/_flash.html.erb
<% if notice ||  alert %>
  <% flash_type = notice ? "notice" : "error" %>
  <div class="fixed inset-x-0 top-0 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
    <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded px-4 py-3 rounded relative <%= tailwind_classes_for(flash_type) %> pointer-events-auto">
      <div class="p-2">
        <div class="flex items-start">
          <div class="ml-3 w-0 flex-1 pt-0.5">
            <p class="text-sm leading-5 font-medium">
              <%= notice || alert %>
            </p>
          </div>
          <div class="ml-4 flex-shrink-0 flex">
            <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- navbar -->
<nav class="flex justify-between w-screen">
  <div class="px-5 xl:px-12 py-6 flex w-full justify-between">
    <a class="text-3xl font-bold" href="/">
      School
    </a>
    <!-- Big menu -->
    <ul class="hidden md:flex px-4 mx-auto font-semibold font-heading space-x-12">
      <li><a class="hover:text-gray-200" href="/">home</a></li>
      <li><%= link_to 'courses', courses_path, class: "hover:text-gray-200" %></li>
      <li><%= link_to 'promotions', promotions_path, class: "hover:text-gray-200" %></li>
      <hr class="mx-5">
      <li><%= link_to 'student ?', new_student_session_path, class: "hover:text-gray-200" %></li>
      <li><%= link_to 'teacher ?', new_teacher_session_path, class: "hover:text-gray-200" %></li>
    </ul>
    <!-- User dropdown -->
    <div class="hidden md:flex text-sm px-4 rounded">
      <div class="relative" data-controller="dropdown">
        <div data-action="click->dropdown#toggle click@window->dropdown#hide"
          data-dropdown-active-target="#dropdown-button"
          data-dropdown-invisible-class="opacity-0 scale-95"
          data-dropdown-entering-class="ease-out duration-100"
          data-dropdown-enter-timeout="100"
          data-dropdown-leaving-class="ease-in duration-75"
          role="button" data-dropdown-target="button" tabindex="0" class="inline-block select-none">
          <span class="appearance-none flex items-center inline-block text-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 hover:text-gray-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </span>
        </div>
        <div data-dropdown-target="menu" class="absolute right-0 mt-2 hidden rounded-md shadow-lg ring-black divide-y divide-gray-100 focus:outline-none bg-white z-50">
          <% if user_signed_in? %>
            <div class="block px-4 py-2">
              <span class="block text-sm py-2"><%= current_user.full_name %></span>
              <span class="block text-sm font-medium text-gray-900 truncate"><%= current_user.email %></span>
            </div>
            <div class="py-1">
              <% if current_user.is_a?(Student) %>
                <%= button_to 'Edit profile', edit_student_registration_path, method: :get, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>            </div>
              <%= button_to 'Sign Out', destroy_student_session_path, method: :delete, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
            <% elsif current_user.is_a?(Teacher) %>
              <%= button_to 'Edit profile', edit_teacher_registration_path, method: :get, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>            </div>
            <%= button_to 'Sign Out', destroy_teacher_session_path, method: :delete, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
          <% end %>
        <% else %>
          <a class="block px-4 py-2 text-md hover:text-gray-200" href="#" data-action="dropdown#toggle">Login</a>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Small menu dropdown -->
  <div class="md:hidden flex items-center" data-controller="dropdown">
    <button class="outline-none mobile-menu-button" data-action="click->dropdown#toggle click@window->dropdown#hide"
      data-dropdown-active-target="#dropdown-button"
      data-dropdown-invisible-class="opacity-0 scale-95"
      data-dropdown-visible-class="opacity-100 scale-100"
      data-dropdown-entering-class="ease-out duration-100"
      data-dropdown-enter-timeout="100"
      data-dropdown-leaving-class="ease-in duration-75"
      role="button" data-dropdown-target="button" tabindex="0">
      <svg class="w-6 h-6 text-gray-700 hover:text-gray-200" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M4 6h16M4 12h16M4 18h16"></path>
      </svg>
    </button>
    <div data-dropdown-target="menu" class="md:hidden flex z-50 absolute top-[var(--h-navbar)] left-0 right-0 inset-x-0 bg-white border border-gray-200 shadow-sm rounded-md">
      <div class="mx-2 w-full">
        <div class="flex flex-col justify-center items-center">
          <a class="block px-4 py-2 text-md hover:text-gray-200" href="#" data-action="dropdown#toggle">home</a>
          <%= link_to 'promotions', promotions_path, class: "block px-4 py-2 text-md hover:text-gray-200", :"data-action" => "dropdown#toggle" %>
          <%= link_to 'courses', courses_path, class: "block px-4 py-2 text-md hover:text-gray-200", :"data-action" => "dropdown#toggle" %>
          <%= link_to 'student ?', new_student_session_path, class: "block px-4 py-2 text-md hover:text-gray-200", :"data-action" => "dropdown#toggle" %>
          <%= link_to 'teacher ?', new_teacher_session_path, class: "block px-4 py-2 text-md hover:text-gray-200", :"data-action" => "dropdown#toggle" %>
        </div>
        <hr class="border-gray-200 pt-2">
        <% if current_user %>
          <div class="block px-4 py-2 flex flex-col justify-center items-center">
            <span class="block text-sm "><%= current_user.first_name  %> <%= current_user.last_name  %></span>
            <span class="block text-sm font-medium text-gray-900 truncate"><%= current_user.email %></span>
          </div>
          <div class="py-1">
            <% if current_user.is_a?(Student) %>
              <%= button_to 'Edit profile', edit_student_registration_path, method: :get, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>            </div>
            <%= button_to 'Sign Out', destroy_student_session_path, method: :delete, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3  text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
          <% elsif current_user.is_a?(Teacher) %>
            <%= button_to 'Edit profile', edit_teacher_registration_path, method: :get, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>            </div>
          <%= button_to 'Sign Out', destroy_teacher_session_path, method: :delete, data: {action: "click->dropdown#toggle"}, class: 'w-full block px-8 py-3  text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
        <% end %>
      </div>
    <% else %>
      <a class="block px-4 py-2 text-md hover:text-gray-200" href="#" data-action="dropdown#toggle">Login</a>
    <% end %>
  </div>
</div>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROR1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container mx-auto flex flex-col items-center">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>